"""empty message

Revision ID: 5778c67b4de9
Revises: a3229957a46f
Create Date: 2021-12-08 12:09:52.850680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5778c67b4de9'
down_revision = 'a3229957a46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('one_time_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'one_time_password')
    # ### end Alembic commands ###
