"""empty message

Revision ID: 83aaff549dba
Revises: 5394e9a80b95
Create Date: 2022-03-07 18:35:40.359551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83aaff549dba'
down_revision = '5394e9a80b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ohlc_data_id', table_name='ohlc_data')
    op.drop_table('ohlc_data')
    op.drop_index('ix_signals_id', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_user_subscriptions_id', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ticker', 'timeframe', name='subscriptions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticker', 'timeframe'], ['subscriptions.ticker', 'subscriptions.timeframe'], name='user_subscriptions_ticker_timeframe_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_subscriptions_pkey')
    )
    op.create_index('ix_user_subscriptions_id', 'user_subscriptions', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('td_up', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('td_down', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ohlc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='signals_pkey')
    )
    op.create_index('ix_signals_id', 'signals', ['id'], unique=False)
    op.create_table('ohlc_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('open', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timeframe', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ticker', 'timeframe'], ['subscriptions.ticker', 'subscriptions.timeframe'], name='ohlc_data_ticker_timeframe_fkey'),
    sa.PrimaryKeyConstraint('id', name='ohlc_data_pkey')
    )
    op.create_index('ix_ohlc_data_id', 'ohlc_data', ['id'], unique=False)
    # ### end Alembic commands ###
